# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionmessage',
            name='api_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exceptionmessage',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
